<a href="https://colab.research.google.com/github/CamilaAvila13/JNE/blob/main/JNE_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
!wget https://github.com/CamilaAvila13/JNE/raw/refs/heads/main/EG2021_2V_Resultados_Presidencial.xlsx

--2026-05-19 22:36:20--  https://github.com/CamilaAvila13/JNE/raw/refs/heads/main/EG2021_2V_Resultados_Presidencial.xlsx
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/CamilaAvila13/JNE/refs/heads/main/EG2021_2V_Resultados_Presidencial.xlsx [following]
--2026-05-19 22:36:20--  https://raw.githubusercontent.com/CamilaAvila13/JNE/refs/heads/main/EG2021_2V_Resultados_Presidencial.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74784 (73K) [application/octet-stream]
Saving to: ‘EG2021_2V_Resultados_Presidencial.xlsx.2’

EG2021_2V_Resultado 100%[===================>]  73.03K  --.-KB/s    in 0.01s

2026-05-19 22:36:21 (5.55 MB/s) - ‘EG2021_2V_Resultados_Presidencial.xlsx.2’ saved [74784/74784]

In [26]:
!pip install pyreadstat

import pyreadstat
import pandas as pd

# Read the excel file, specifying header=4 so the 5th row (index 4) becomes the first row of the DataFrame
df = pd.read_excel("EG2021_2V_Resultados_Presidencial.xlsx.1")

df.head()

Requirement already satisfied: pyreadstat in /usr/local/lib/python3.12/dist-packages (1.3.5)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.20.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)

,Region,Provincia,Electores,Participación,% Participación,Ausentismo,% Ausentismo,Votos emitidos,% Votos emitidos,Votos válidos,% Votos válidos,Organización Política,Tipo Organización Política,Votos,% Votos
0,AMAZONAS,CHACHAPOYAS,40752,28447,0.6981,12305,0.3019,28447,0.6981,26144,0.6415,FUERZA POPULAR,PARTIDO POLÍTICO,10473,0.4006
1,AMAZONAS,CHACHAPOYAS,40752,28447,0.6981,12305,0.3019,28447,0.6981,26144,0.6415,PARTIDO POLITICO NACIONAL PERU LIBRE,PARTIDO POLÍTICO,15671,0.5994
2,AMAZONAS,CHACHAPOYAS,40752,28447,0.6981,12305,0.3019,28447,0.6981,26144,0.6415,VOTOS EN BLANCO,NaN,274,0.0105
3,AMAZONAS,CHACHAPOYAS,40752,28447,0.6981,12305,0.3019,28447,0.6981,26144,0.6415,VOTOS NULOS,NaN,2029,0.0776
4,AMAZONAS,BAGUA,62110,38970,0.6274,23140,0.3726,38970,0.6274,36750,0.5917,FUERZA POPULAR,PARTIDO POLÍTICO,10770,0.2931

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 784 entries, 0 to 783
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Region                      784 non-null    object
 1   Provincia                   784 non-null    object
 2   Electores                   784 non-null    int64
 3   Participación               784 non-null    int64
 4   % Participación             784 non-null    float64
 5   Ausentismo                  784 non-null    int64
 6   % Ausentismo                784 non-null    float64
 7   Votos emitidos              784 non-null    int64
 8   % Votos emitidos            784 non-null    float64
 9   Votos válidos               784 non-null    int64
 10  % Votos válidos             784 non-null    float64
 11  Organización Política       784 non-null    object
 12  Tipo Organización Política  392 non-null    object
 13  Votos                       784 non-null    int64
 14  % Votos                     784 non-null    float64
dtypes: float64(5), int64(6), object(4)
memory usage: 92.0+ KB

In [32]:
columns_to_drop = ['Region', 'Provincia', 'Electores', 'Participación','% Participación','Ausentiso', '% Ausentismo', 'Votos emitidos','% Votos emitidos', 'Votos válidos', '% Votos válidos', 'Ausentismo','Organización Política', 'Tipo Organización Política']
df = df.drop(columns=columns_to_drop, errors='ignore')
display(df.head())

   Votos  % Votos
0  10473   0.4006
1  15671   0.5994
2    274   0.0105
3   2029   0.0776
4  10770   0.2931

In [33]:
df.to_excel('Data_Camila_subset.xlsx', index=False)
print('DataFrame saved to Data_Camila_subset.xlsx')

DataFrame saved to Data_Camila_subset.xlsx

In [34]:
from google.colab import files
files.download('Data_Camila_subset.xlsx')